# Generated by Django 5.1.4 on 2025-02-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_orderupdate_rename_description_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
    ]
